### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by emilyhorsman** [emilyhorsman/haskell-resources#4]
I've been going through the CIS 194 homework in my repo [here](https://github.com/emilyhorsman/cis194) (spoiler warning).

Do we want to be putting exercise solutions (from CIS 194 or other sources) in this repo? If so, how do we want to organize them? `$filename.$person.hs`? `/$exercise/$person/$filename.hs`?

**Comment by jnlon** [comment]
I kinda like

/$person/$exercise/$filename.hs

So if we want to make little side experiments we can put them under our folder.

**Comment by emilyhorsman** [comment]
👍
